//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTipoDeduccion
    {
        public CatalogoTipoDeduccion()
        {
            this.DetalleDeducciones = new HashSet<DetalleDeducciones>();
            this.RubroDeduccion = new HashSet<RubroDeduccion>();
        }
    
        public int PK_CatalogoTipoDeduccion { get; set; }
        public Nullable<int> FK_TipoDeduccion { get; set; }
        public Nullable<System.DateTime> FecInicio { get; set; }
        public Nullable<System.DateTime> FecFinal { get; set; }
    
        public virtual TipoDeduccion TipoDeduccion { get; set; }
        public virtual ICollection<DetalleDeducciones> DetalleDeducciones { get; set; }
        public virtual ICollection<RubroDeduccion> RubroDeduccion { get; set; }
    }
}
