//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoRubroDeduccion
    {
        public CatalogoRubroDeduccion()
        {
            this.RubroDeduccion = new HashSet<RubroDeduccion>();
        }
    
        public int PK_CatalogoRubroDeduccion { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<RubroDeduccion> RubroDeduccion { get; set; }
    }
}
