//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRubro
    {
        public int PK_DetalleRubro { get; set; }
        public Nullable<int> FK_DetalleDiferenciaSalarial { get; set; }
        public Nullable<int> FK_ComponenteSalarial { get; set; }
        public Nullable<double> MontoAnterior { get; set; }
        public Nullable<double> MontoActual { get; set; }
    
        public virtual ComponenteSalarial ComponenteSalarial { get; set; }
        public virtual DetalleDiferenciaSalarial DetalleDiferenciaSalarial { get; set; }
    }
}
