//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDiferenciaSalarial
    {
        public DetalleDiferenciaSalarial()
        {
            this.DetalleDeducciones = new HashSet<DetalleDeducciones>();
            this.DetalleRubro = new HashSet<DetalleRubro>();
        }
    
        public int PK_DetalleDiferenciaSalarial { get; set; }
        public Nullable<int> FK_DiferenciaSalarial { get; set; }
        public Nullable<int> FK_PorcentajeRenta { get; set; }
        public Nullable<int> FK_PorcentajeSalarioEscolar { get; set; }
        public Nullable<System.DateTime> FecInicio { get; set; }
        public Nullable<System.DateTime> FecFinal { get; set; }
        public Nullable<double> TotalSalarioEscolar { get; set; }
        public Nullable<double> TotalRenta { get; set; }
        public Nullable<double> TotalDeduccionesObrero { get; set; }
        public Nullable<double> TotalDeduccionesPatronal { get; set; }
        public Nullable<double> TotalAguinaldo { get; set; }
        public Nullable<double> TotalDiferencia { get; set; }
    
        public virtual ICollection<DetalleDeducciones> DetalleDeducciones { get; set; }
        public virtual DiferenciaSalarial DiferenciaSalarial { get; set; }
        public virtual PorcentajeRenta PorcentajeRenta { get; set; }
        public virtual PorcentajeSalarioEscolar PorcentajeSalarioEscolar { get; set; }
        public virtual ICollection<DetalleRubro> DetalleRubro { get; set; }
    }
}
