//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorcentajeSalarioEscolar
    {
        public PorcentajeSalarioEscolar()
        {
            this.DetalleDiferenciaSalarial = new HashSet<DetalleDiferenciaSalarial>();
        }
    
        public int PK_PorcentajeSalarioEscolar { get; set; }
        public string NumResolucion { get; set; }
        public Nullable<double> PorcEscolar { get; set; }
        public Nullable<System.DateTime> FecInicio { get; set; }
        public Nullable<System.DateTime> FecFinal { get; set; }
    
        public virtual ICollection<DetalleDiferenciaSalarial> DetalleDiferenciaSalarial { get; set; }
    }
}
