//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorcentajeRenta
    {
        public PorcentajeRenta()
        {
            this.DetalleDiferenciaSalarial = new HashSet<DetalleDiferenciaSalarial>();
        }
    
        public int PK_PorcentajeRenta { get; set; }
        public Nullable<double> PorcRenta { get; set; }
        public Nullable<System.DateTime> FecInicio { get; set; }
        public Nullable<System.DateTime> FecFinal { get; set; }
        public Nullable<double> RangoInicial { get; set; }
        public Nullable<double> RangoFinal { get; set; }
    
        public virtual ICollection<DetalleDiferenciaSalarial> DetalleDiferenciaSalarial { get; set; }
    }
}
