//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubroDeduccion
    {
        public int PK_RubroDeduccion { get; set; }
        public Nullable<int> FK_CatalogoTipoDeduccion { get; set; }
        public Nullable<int> FK_CatalogoRubroDeduccion { get; set; }
        public Nullable<double> PorcRubro { get; set; }
    
        public virtual CatalogoRubroDeduccion CatalogoRubroDeduccion { get; set; }
        public virtual CatalogoTipoDeduccion CatalogoTipoDeduccion { get; set; }
    }
}
